// Generates load_legacy.sql from the consistent SQLite snapshot.
// Read-only against SQLite; emits a single transactional SQL script.
import { DatabaseSync } from 'node:sqlite'
import { randomUUID } from 'node:crypto'
import { writeFileSync } from 'node:fs'

const db = new DatabaseSync(process.argv[2], { readOnly: true })
const out = []
const W = (s) => out.push(s)

// --- literal helpers -------------------------------------------------------
// standard_conforming_strings is on by default in PG, so backslashes are
// literal and doubling single quotes is sufficient.
const S = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const B = (v) => (v === null || v === undefined ? 'null' : v ? 'true' : 'false')
const N = (v) => (v === null || v === undefined ? 'null' : String(Number(v)))
// Legacy stored naive datetime.utcnow(); interpret as UTC.
const TS = (v) => (v === null || v === undefined || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}+00'::timestamptz`)
const J = (v, fallback) => {
  if (v === null || v === undefined || v === '') return `'${fallback}'::jsonb`
  const s = typeof v === 'string' ? v : JSON.stringify(v)
  try { JSON.parse(s) } catch { return `'${fallback}'::jsonb` }
  return `${S(s)}::jsonb`
}

W('-- Generated by build_loader.mjs from a SQLite backup-API snapshot.')
W('-- Idempotent: truncates the target tables, then loads. Safe to re-run.')
W('begin;')
W('')
W('truncate table')
W('  public.traceability_link_posts, public.traceability_links, public.editorial_assets,')
W('  public.generation_requests, public.anonymized_posts_current, public.analyzed_posts,')
W('  public.normalized_posts, public.raw_posts, public.sources, public.configurations')
W('  restart identity cascade;')
W('')

// --- sources ---------------------------------------------------------------
const sources = db.prepare('select * from sources').all()
W(`-- sources (${sources.length})`)
for (const s of sources) {
  W(`insert into public.sources (id, name, source_type, url, company_name, collection_frequency, enabled, last_fetched_at, created_at, updated_at) values (${S(s.id)}, ${S(s.name)}, ${S(s.source_type)}, ${S(s.url)}, ${S(s.company_name)}, ${S(s.collection_frequency ?? 'daily')}, ${B(s.enabled)}, ${TS(s.last_fetched_at)}, ${TS(s.created_at)}, ${TS(s.updated_at)});`)
}
W('')

// --- raw_posts: surrogate uuid PK, legacy_id preserved ---------------------
const rawPosts = db.prepare('select * from raw_posts').all()
const idMap = new Map() // legacy string id -> new uuid
for (const r of rawPosts) idMap.set(r.id, randomUUID())

// The LinkedIn activity URN, recovered from the permalink. The legacy schema
// never stored it; the scraper's own PK is exactly this value. Posts with no
// recoverable id (e.g. source_url = 'manual') get NULL, which the partial
// unique index leaves unconstrained.
const EXT = /(?:activity|ugcPost)-(\d{10,})/
let withExt = 0, withoutExt = 0
W(`-- raw_posts (${rawPosts.length}) -- content_hash and canonical_url are GENERATED, not inserted`)
for (const r of rawPosts) {
  const m = EXT.exec(r.source_url ?? '')
  if (m) withExt++; else withoutExt++
  W(`insert into public.raw_posts (id, legacy_id, source_id, source_url, external_post_id, post_title, post_text, author, published_at, collected_at, media_urls, engagement_metrics, is_processed, created_at, updated_at) values (${S(idMap.get(r.id))}, ${S(r.id)}, ${S(r.source_id)}, ${S(r.source_url)}, ${m ? S(m[1]) : 'null'}, ${S(r.post_title)}, ${S(r.post_text)}, ${S(r.author)}, ${TS(r.published_at)}, ${TS(r.collected_at)}, ${J(r.media_urls, '[]')}, ${J(r.engagement_metrics, '{}')}, ${B(r.is_processed)}, ${TS(r.created_at)}, ${TS(r.updated_at)});`)
}
W('')

// --- normalized_posts ------------------------------------------------------
const norm = db.prepare('select * from normalized_posts').all()
W(`-- normalized_posts (${norm.length})`)
for (const n of norm) {
  W(`insert into public.normalized_posts (id, raw_post_id, clean_text, extracted_hashtags, extracted_mentions, tone_type, word_count, language, created_at) values (${S(randomUUID())}, ${S(idMap.get(n.raw_post_id))}, ${S(n.clean_text)}, ${J(n.extracted_hashtags, '[]')}, ${J(n.extracted_mentions, '[]')}, ${S(n.tone_type)}, ${N(n.word_count)}, ${S(n.language ?? 'en')}, ${TS(n.created_at)});`)
}
W('')

// --- analyzed_posts (cluster_id dropped) -----------------------------------
const analyzed = db.prepare('select * from analyzed_posts').all()
W(`-- analyzed_posts (${analyzed.length}) -- legacy cluster_id dropped (all NULL)`)
for (const a of analyzed) {
  W(`insert into public.analyzed_posts (id, raw_post_id, relevance_scores, overall_relevance, reason_for_score, included_in_generation, topics, entities, key_phrases, created_at, updated_at) values (${S(randomUUID())}, ${S(idMap.get(a.raw_post_id))}, ${J(a.relevance_scores, '{}')}, ${N(a.overall_relevance)}, ${S(a.reason_for_score)}, ${B(a.included_in_generation)}, ${J(a.topics, '[]')}, ${J(a.entities, '{}')}, ${J(a.key_phrases, '[]')}, ${TS(a.created_at)}, ${TS(a.created_at)});`)
}
W('')

// --- anonymized_posts_current ---------------------------------------------
const anon = db.prepare('select * from anonymized_posts_current').all()
W(`-- anonymized_posts_current (${anon.length})`)
for (const a of anon) {
  W(`insert into public.anonymized_posts_current (raw_post_id, source_name, generalized_source_name, overall_relevance, anonymized_text, replacements, config_snapshot, updated_at) values (${S(idMap.get(a.raw_post_id))}, ${S(a.source_name)}, ${S(a.generalized_source_name)}, ${N(a.overall_relevance)}, ${S(a.anonymized_text)}, ${J(a.replacements, '[]')}, ${J(a.config_snapshot, '{}')}, ${TS(a.updated_at)});`)
}
W('')

// --- generation_requests ---------------------------------------------------
const genreqs = db.prepare('select * from generation_requests').all()
W(`-- generation_requests (${genreqs.length}) -- created_by dropped: legacy values are not auth.users ids`)
for (const g of genreqs) {
  W(`insert into public.generation_requests (id, generation_type, collection_period_start, collection_period_end, selected_sources, user_instructions, status, error_message, created_by, created_at, updated_at) values (${S(g.id)}, ${S(g.generation_type)}, ${TS(g.collection_period_start)}, ${TS(g.collection_period_end)}, ${J(g.selected_sources, '[]')}, ${S(g.user_instructions)}, ${S(g.status ?? 'completed')}, ${S(g.error_message)}, null, ${TS(g.created_at)}, ${TS(g.updated_at)});`)
}
W('')

// --- editorial_assets: provenance classification --------------------------
// The legacy _simulated_llm fallback emits a fixed block of copy. Assets that
// contain its signature phrase are provably canned; the rest are genuinely
// unknown and must not be presented as verified.
const assets = db.prepare('select * from editorial_assets').all()
let nSim = 0, nUnv = 0
W(`-- editorial_assets (${assets.length}) -- all is_legacy = true`)
for (const e of assets) {
  const simulated = /not a stereotype/i.test(e.generated_text ?? '')
  if (simulated) nSim++; else nUnv++
  const provenance = simulated ? 'simulated_fallback' : 'legacy_unverified'
  const llmUsed = simulated ? 'false' : 'null' // null = unknown, never inferred
  W(`insert into public.editorial_assets (id, generation_id, variant_number, asset_type, title, generated_text, featured_clusters, featured_sources, hashtags, cta_text, status, is_legacy, provenance, llm_used, approved_by, approval_timestamp, approval_notes, feedback_provided, edits_made, created_at, updated_at) values (${S(e.id)}, ${S(e.generation_id)}, ${N(e.variant_number ?? 1)}, ${S(e.asset_type)}, ${S(e.title)}, ${S(e.generated_text)}, ${J(e.featured_clusters, '[]')}, ${J(e.featured_sources, '[]')}, ${J(e.hashtags, '[]')}, ${S(e.cta_text)}, ${S(e.status ?? 'draft')}, true, ${S(provenance)}, ${llmUsed}, null, ${TS(e.approval_timestamp)}, ${S(e.approval_notes)}, ${S(e.feedback_provided)}, ${J(e.edits_made, '[]')}, ${TS(e.created_at)}, ${TS(e.updated_at)});`)
}
W('')

// --- traceability_links + normalised join table ---------------------------
const links = db.prepare('select * from traceability_links').all()
W(`-- traceability_links (${links.length})`)
for (const l of links) {
  W(`insert into public.traceability_links (id, asset_id, claim_text, confidence, position_in_asset, created_at) values (${S(l.id)}, ${S(l.asset_id)}, ${S(l.claim_text)}, ${S(l.confidence ?? 'high')}, ${N(l.position_in_asset)}, ${TS(l.created_at)});`)
}
W('')

let refCount = 0, unresolved = 0
W('-- traceability_link_posts: JSON array -> rows with enforced FKs')
for (const l of links) {
  let arr
  try { arr = JSON.parse(l.source_post_ids) } catch { arr = [] }
  arr.forEach((legacyPostId, position) => {
    const mapped = idMap.get(legacyPostId)
    if (!mapped) { unresolved++; return }
    refCount++
    W(`insert into public.traceability_link_posts (link_id, raw_post_id, position) values (${S(l.id)}, ${S(mapped)}, ${position});`)
  })
}
W('')

// --- configurations --------------------------------------------------------
const cfg = db.prepare('select * from configurations').all()
W(`-- configurations (${cfg.length})`)
for (const c of cfg) {
  W(`insert into public.configurations (id, themes, anonymization_enabled, anonymize_companies, keep_public_bodies, company_aliases, voice_tone, voice_audience, voice_style, min_relevance_score, updated_at) values ('default', ${J(c.themes, '[]')}, ${B(c.anonymization_enabled)}, ${B(c.anonymize_companies)}, ${B(c.keep_public_bodies)}, ${J(c.company_aliases, '{}')}, ${S(c.voice_tone)}, ${S(c.voice_audience)}, ${S(c.voice_style)}, ${N(c.min_relevance_score)}, ${TS(c.updated_at)});`)
}

W('')
W('commit;')

writeFileSync(process.argv[3], out.join('\n') + '\n', 'utf8')

console.log(`sources=${sources.length} raw_posts=${rawPosts.length} normalized=${norm.length} analyzed=${analyzed.length}`)
console.log(`anonymized=${anon.length} genreqs=${genreqs.length} assets=${assets.length} links=${links.length}`)
console.log(`external_post_id: recovered=${withExt} null=${withoutExt}`)
console.log(`link_post_refs=${refCount} unresolved=${unresolved}`)
console.log(`provenance: simulated_fallback=${nSim} legacy_unverified=${nUnv}`)
console.log(`configurations=${cfg.length}`)
console.log(`wrote ${process.argv[3]}`)
db.close()
